-- SQL script to delete or truncate all data from all tables in the schema
-- Generated on: 2025-04-22
-- Note: Ensure no active transactions or locks before running
-- Warning: This will permanently remove all data

-- Option 1: DELETE FROM (respects foreign keys, preserves auto-increment)
-- Execute in this order to avoid foreign key constraint violations

-- Child tables
DELETE FROM DETALLE_CARRITO;
DELETE FROM DETALLE_DEVOLUCION;
DELETE FROM DETALLE_VENTA;
DELETE FROM DETALLE_LOTE;
DELETE FROM IMPUESTO_DOCUMENTO;
DELETE FROM PAGO;
DELETE FROM LOG;
DELETE FROM TOKEN_RECUPERACION;

-- Mid-level tables
DELETE FROM CARRITO;
DELETE FROM ORDEN_DEVOLUCION;
DELETE FROM DOCUMENTO_DE_VENTAS;
DELETE FROM INVENTARIO;
DELETE FROM LOTE;
DELETE FROM IMPUESTO_PERIODO;
DELETE FROM MONEDA_PERIODO;

-- Parent tables
DELETE FROM ORDEN_DE_VENTA;
DELETE FROM DOCUMENTO_COMPRAS;
DELETE FROM PRODUCTO;
DELETE FROM METODO_DE_PAGO;

-- Top-level tables
DELETE FROM ADMIN;
DELETE FROM CLIENTE;
DELETE FROM USUARIO;
DELETE FROM CATEGORIA;
DELETE FROM MARCA;
DELETE FROM PROVEEDOR;
DELETE FROM IMPUESTO;
DELETE FROM PERIODO;
DELETE FROM MONEDA;

-- Option 2: TRUNCATE TABLE (faster, resets auto-increment, requires disabling foreign keys)
-- Uncomment to use; ensure no other sessions are accessing the database


SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE ADMIN;
TRUNCATE TABLE CARRITO;
TRUNCATE TABLE CATEGORIA;
TRUNCATE TABLE CLIENTE;
TRUNCATE TABLE DETALLE_CARRITO;
TRUNCATE TABLE DETALLE_DEVOLUCION;
TRUNCATE TABLE DETALLE_LOTE;
TRUNCATE TABLE DETALLE_VENTA;
TRUNCATE TABLE DOCUMENTO_COMPRAS;
TRUNCATE TABLE DOCUMENTO_DE_VENTAS;
TRUNCATE TABLE IMPUESTO;
TRUNCATE TABLE IMPUESTO_DOCUMENTO;
TRUNCATE TABLE IMPUESTO_PERIODO;
TRUNCATE TABLE INVENTARIO;
TRUNCATE TABLE LOG;
TRUNCATE TABLE LOTE;
TRUNCATE TABLE MARCA;
TRUNCATE TABLE METODO_DE_PAGO;
TRUNCATE TABLE MONEDA;
TRUNCATE TABLE MONEDA_PERIODO;
TRUNCATE TABLE ORDEN_DEVOLUCION;
TRUNCATE TABLE ORDEN_DE_VENTA;
TRUNCATE TABLE PAGO;
TRUNCATE TABLE PERIODO;
TRUNCATE TABLE PRODUCTO;
TRUNCATE TABLE PROVEEDOR;
TRUNCATE TABLE USUARIO;
TRUNCATE TABLE TOKEN_RECUPERACION;

SET FOREIGN_KEY_CHECKS = 1;

DROP TABLE IF EXISTS LOG;
DROP TABLE IF EXISTS PAGO;
DROP TABLE IF EXISTS METODO_DE_PAGO;
DROP TABLE IF EXISTS MONEDA_PERIODO;
DROP TABLE IF EXISTS MONEDA;
DROP TABLE IF EXISTS IMPUESTO_DOCUMENTO;
DROP TABLE IF EXISTS IMPUESTO_PERIODO;
DROP TABLE IF EXISTS PERIODO;
DROP TABLE IF EXISTS IMPUESTO;
DROP TABLE IF EXISTS INVENTARIO;
DROP TABLE IF EXISTS DETALLE_LOTE;
DROP TABLE IF EXISTS LOTE;
DROP TABLE IF EXISTS DOCUMENTO_COMPRAS;
DROP TABLE IF EXISTS PROVEEDOR;
DROP TABLE IF EXISTS DETALLE_DEVOLUCION;
DROP TABLE IF EXISTS ORDEN_DEVOLUCION;
DROP TABLE IF EXISTS DOCUMENTO_DE_VENTAS;
DROP TABLE IF EXISTS DETALLE_VENTA;
DROP TABLE IF EXISTS ORDEN_DE_VENTA;
DROP TABLE IF EXISTS DETALLE_CARRITO;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS MARCA;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS CARRITO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS ADMIN;
DROP TABLE IF EXISTS TOKEN_RECUPERACION;
DROP TABLE IF EXISTS USUARIO;